version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 12
    environment:
      FL_OUTPUT_DIR: output

    steps:
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: Techno_Task

      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output

workflows:
  build-test-lint:
    jobs:
      - build-and-test
